name: cicd
on: 
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  ci:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      # Step 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Configurar JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Build Maven sem testes
      - name: Build JAR
        run: ./mvnw clean package -DskipTests

      # Step 4: Gerar tag da imagem Docker
      - name: Set image tag
        id: set_tag
        run: echo "tag=ci-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      # Step 5: Login Docker (Docker Hub ou GHCR)
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      # Step 6: Push Docker image
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: | 
            luizflavios/drivercore:${{ steps.set_tag.outputs.tag }}
            luizflavios/drivercore:latest

  cd:
    name: Deploy
    runs-on: ubuntu-latest
    needs: ci
    steps:
      # Step 1: Conectar à VPS via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /etc/icontainer/docker/compose/drivecore
            # Atualiza a imagem no docker-compose.yml ou usa a tag
            docker-compose pull
            docker-compose up -d
                        
